apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crud-veiculos-pvc
  namespace: default
  labels:
    app: crud-veiculos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
